server:
  port: 8082
spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:mysql://localhost:3306/ticket?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true


#jwt:
#  secret: fewbiuebeot5324980hbhgsd0uub9gpkklnqbp4214989oub926t32be0gbdsn
#

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    enabled: false
#    enabled: false  유레카 연결할때 지우기
  instance:
    prefer-ip-address: true

