server:
  port: 8003
spring:
  application:
    name: reservation-service
  datasource:
    url: jdbc:mysql://localhost:3306/busreservation?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  resources:
  static-locations: classpath:/static/
