spring:
  datasource:
    url: jdbc:mysql://localhost:3306/terminal?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  resources:
  static-locations: classpath:/static/
server:
  port : 8082
